// 定义装饰器类型（标记方法为工具动作）
interface ToolActionMetadata {
    _isToolAction: boolean;
    _toolName?: string | undefined;
    _toolDescription?: string | undefined;
}

/**
 * 类型校验错误异常
 */
export class TypeValidationError extends Error {
    public paramName: string;
    public expectedType: string;
    public actualType: string;
    public value: any;

    constructor(
        message: string,
        paramName: string,
        expectedType: string,
        actualType: string,
        value: any
    ) {
        super(message);
        this.name = 'TypeValidationError';
        this.paramName = paramName;
        this.expectedType = expectedType;
        this.actualType = actualType;
        this.value = value;
    }
}

// 存储方法元数据的映射表（类实例 -> 方法名 -> 元数据）
const toolActionMetadataMap = new Map<object, Map<string, ToolActionMetadata>>();

/**
 * 装饰器工厂：创建用于标记方法为工具action的装饰器
 *
 * 该装饰器将类方法标记为可展开的工具action，使其能够在运行时被识别和调用
 *
 * @param name 工具名称（可选）
 *        - 如果提供：使用指定的名称
 *        - 如果不提供：从方法名自动生成（下划线替换为点号）
 * @param description 工具描述（可选）
 *        - 如果提供：使用指定的描述
 *        - 如果不提供：从方法的JSDoc注释中提取
 *
 * @returns PropertyDecorator 装饰器函数
 *
 * 使用示例：
 *     @toolAction("memory.add", "向记忆库添加新信息")
 *     _addMemory(content: string, importance: number = 0.5): string {
 *         // 实现记忆添加逻辑
 *         return "记忆已添加";
 *     }
 *
 * 另一种用法（不指定名称和描述）：
 *     @toolAction()
 *     _searchMemory(query: string): string {
 *         // 实现记忆搜索逻辑
 *         return "搜索结果";
 *     }
 */
export function toolAction(name?: string, description?: string) {
    return function (target: object, propertyKey: string, descriptor: PropertyDescriptor) {
        // 检查目标对象是否已存在于元数据映射中
        if (!toolActionMetadataMap.has(target)) {
            toolActionMetadataMap.set(target, new Map());
        }

        const methodMap = toolActionMetadataMap.get(target)!;

        methodMap.set(propertyKey, {
            _isToolAction: true,
            _toolName: name,
            _toolDescription: description
        });

        return descriptor;
    };
}

/**
 * 工具参数定义
 */
export interface ToolParameter {
    name: string;
    type: string;
    description: string;
    required: boolean;
    default: any;
}

/**
 * 工具基类
 * 
 *  支持两种使用模式：
 *  1. 普通模式：工具作为单一实体使用
 *  2. 可展开模式：工具可以展开为多个独立的子工具（每个子工具对应一个功能）
 *
 *  展开模式支持两种实现方式：
 *  - 手动定义子工具类（传统方式）
 *  - 使用 @toolAction 装饰器自动生成（推荐）
 */
export abstract class Tool {
    public name: string;
    public description: string;
    public expandable: boolean;

    /**
     * 初始化工具
     * 
     * @param name 工具名称
     * @param description 工具描述
     * @param expandable 是否可展开为多个子工具
     */
    constructor({
        name,
        description,
        expandable = false
    }: {
        name: string,
        description: string,
        expandable?: boolean
    }) {
        this.name = name;
        this.description = description;
        this.expandable = expandable;
    }

    // 执行工具
    abstract run(parameters: Record<string, any>): Promise<string>;

    // 获取工具参数定义
    abstract getParameters(): ToolParameter[];

    /**
     *  获取展开后的子工具列表

        默认实现：自动从标记了 @toolAction 的方法生成子工具
        子类可以重写此方法提供自定义的展开逻辑

        @returns 如果工具支持展开，返回子工具列表；否则返回 null
        
     */
    getExpandedTools(): Tool[] | null {
        if (!this.expandable) {
            return null;
        }

        // 获取当前类和父类的所有元数据（继承链合并）
        const allMethodMetadata = this.getAllMethodMetadata();
        if (!allMethodMetadata || allMethodMetadata.size === 0) {
            return null; // 没有任何标记了@toolAction的方法
        }

        const tools: Tool[] = [];

        for (const [name, metadata] of Array.from(allMethodMetadata.entries())) {
            if ('_isToolAction' in metadata && metadata._isToolAction) {
                // 检查方法是否在当前类中存在（可能被继承或重写）
                const method = (this as any)[name];
                if (method && typeof method === 'function') {
                    const tool = new AutoGeneratedTool({
                        parent: this,
                        method,
                        name: metadata._toolName || name,
                        description: metadata._toolDescription || ""
                    });

                    tools.push(tool);
                }
            }
        }

        return tools.length > 0 ? tools : null;
    }

    /**
     * 获取当前类及继承链上所有类的装饰器元数据
     *
     * @returns Map<string, ToolActionMetadata> 包含所有方法的元数据
     */
    private getAllMethodMetadata(): Map<string, ToolActionMetadata> {
        const allMetadata = new Map<string, ToolActionMetadata>();
        
        // 收集当前类和所有父类的元数据
        let currentClass: any = this;
        const processedClasses = new Set<object>();
        
        while (currentClass && currentClass !== Object.prototype) {
            // 避免循环引用
            if (processedClasses.has(currentClass)) {
                break;
            }
            processedClasses.add(currentClass);
            
            const classMetadata = toolActionMetadataMap.get(currentClass);
            if (classMetadata) {
                // 合并元数据，子类同名方法会覆盖父类方法
                for (const [methodName, metadata] of classMetadata.entries()) {
                    allMetadata.set(methodName, metadata);
                }
            }
            
            // 移动到父类
            currentClass = Object.getPrototypeOf(currentClass);
            
            // 跳过 Tool 基类
            if (currentClass && currentClass.constructor === Tool) {
                break;
            }
        }
        
        return allMetadata;
    }

    /**
     * 验证参数是否满足要求
     *
     * @param parameters 要验证的参数对象
     * @returns 如果所有必需参数都存在返回 true，否则返回 false
     */
    validateParameters(parameters: Record<string, any>): boolean {
        const requiredParams: string[] = [];
        for (const item of this.getParameters()) {
            if (item.required) {
                requiredParams.push(item.name);
            }
        }

        return requiredParams.every((item) => item in parameters);
    }

    /**
     * 转换为字典格式
     *
     * @returns 包含工具信息的字典对象
     */
    toDict(): Record<string, any> {
        return {
            name: this.name,
            description: this.description,
            parameters: this.getParameters().map(param => ({
                name: param.name,
                type: param.type,
                description: param.description,
                required: param.required,
                default: param.default
            }))
        };
    }

    /**
     * 转换为 OpenAI function calling schema 格式
     *
     * 用于 FunctionCallAgent，使工具能够被 OpenAI 原生 function calling 使用
     *
     * @returns 符合 OpenAI function calling 标准的 schema
     */
    toOpenAISchema(): Record<string, any> {
        const parameters = this.getParameters();

        const properties: Record<string, any> = {};
        const required: string[] = [];

        for (const param of parameters) {
            // 基础属性定义
            const prop: Record<string, any> = {
                type: param.type,
                description: param.description
            };

            // 如果有默认值，添加到描述中（OpenAI schema 不支持 default 字段）
            if (param.default !== undefined) {
                prop.description = `${param.description} (默认: ${param.default})`;
            }

            // 如果是数组类型，添加 items 定义
            if (param.type === "array") {
                prop.items = { type: "string" }; // 默认字符串数组
            }

            properties[param.name] = prop;

            // 收集必需参数
            if (param.required) {
                required.push(param.name);
            }
        }

        return {
            type: "function",
            function: {
                name: this.name,
                description: this.description,
                parameters: {
                    type: "object",
                    properties: properties,
                    required: required
                }
            }
        };
    }

    toString(): string {
        return `Tool(name=${this.name})`;
    }
}

class AutoGeneratedTool extends Tool {
    public parent: Tool;
    public method: (...args: any[]) => any;
    private _parameters: ToolParameter[];

    constructor({
        parent,
        method,
        name,
        description
    }: {
        parent: Tool,
        method: (...args: any[]) => any,
        name: string,
        description: string
    }) {
        // 生成工具名称：如果未提供，则按规则自动生成
        const finalName = name || AutoGeneratedTool.generateName(parent.name, method.name);

        // 提取描述：如果未提供，则尝试从方法的 JSDoc 注释中提取
        const finalDescription = description || AutoGeneratedTool.extractDescription(method);

        super({
            name: finalName,
            description: finalDescription
        });

        this.parent = parent;
        this.method = method;

        // 自动解析参数
        this._parameters = AutoGeneratedTool.parseParameters(method);
    }

    /**
     * 根据父工具名和方法名生成工具名
     *
     * @param parentName 父工具名称
     * @param methodName 方法名称
     * @returns 生成的工具名称
     */
    private static generateName(parentName: string, methodName: string): string {
        // 去掉方法名前缀的下划线，并转换为小写蛇形
        const cleanMethod = methodName.replace(/^_+/, '').replace(/([A-Z])/g, '_$1').toLowerCase();
        return `${parentName}.${cleanMethod}`;
    }

    /**
     * 从方法的 JSDoc 注释中提取第一行描述
     *
     * @param method 要提取描述的方法
     * @returns 方法的描述字符串
     */
    private static extractDescription(method: (...args: any[]) => any): string {
        const funcStr = method.toString();
        // 简单匹配 /** ... */ 中的第一行非空行
        const match = funcStr.match(/\/\*\*\s*\n\s*\*\s*([^\n*]+)/);
        if (match) {
            const line = match[1]?.trim() ?? '';
            if (line && !line.toLowerCase().startsWith('@param') && !line.toLowerCase().startsWith('@returns')) {
                return line;
            }
        }
        return `执行 ${method.name}`;
    }

    /**
     * 从方法签名和 JSDoc 自动解析参数列表
     *
     * @param method 要解析的方法
     * @returns 参数定义数组
     */
    private static parseParameters(method: (...args: any[]) => any): ToolParameter[] {
        const funcStr = method.toString();

        // 提取 JSDoc 中的 @param 描述
        const paramDescMap = new Map<string, string>();
        // 支持多行@param描述
        const paramRegex = /@param\s+{[^}]+}\s+(\w+)\s*([\s\S]*?)(?=\*\/|@param|@returns)/g;
        let match;
        while ((match = paramRegex.exec(funcStr)) !== null) {
            const paramName = match[1];
            const paramDesc = match[2];
            if (paramName && paramDesc) {
                paramDescMap.set(paramName, paramDesc.trim());
            }
        }

        // 解析函数参数列表
        const paramsMatch = funcStr.match(/\(([^)]*)\)/);
        if (!paramsMatch) return [];

        const paramsStr = paramsMatch[1]?.trim();
        if (!paramsStr) return [];

        const params: ToolParameter[] = [];

        // 按逗号拆分参数，支持默认值
        paramsStr.split(',').forEach((param) => {
            const [namePart, defaultPart] = param.split('=').map(s => s?.trim() || '');
            const name = namePart?.replace(/:/g, '').trim();
            if (!name || name === 'self' || name === 'this') return; // 跳过 self 和 this

            const required = !defaultPart;
            // 安全的默认值处理（移除不安全的eval使用）
            let defaultVal: any = undefined;
            if (!required && defaultPart) {
                // 简单处理基本类型的默认值
                if (defaultPart === 'true' || defaultPart === 'false') {
                    defaultVal = defaultPart === 'true';
                } else if (!isNaN(Number(defaultPart)) && defaultPart.trim() !== '') {
                    defaultVal = Number(defaultPart);
                } else if ((defaultPart.startsWith('"') && defaultPart.endsWith('"')) ||
                    (defaultPart.startsWith("'") && defaultPart.endsWith("'"))) {
                    defaultVal = defaultPart.slice(1, -1);
                } else {
                    // 对于复杂的默认值，设为undefined避免安全风险
                    defaultVal = undefined;
                }
            }

            // 类型推断：默认 string
            let tsType = 'string';
            if (namePart?.includes(': number')) tsType = 'number';
            else if (namePart?.includes(': boolean')) tsType = 'boolean';
            else if (namePart?.includes(': string[]')) tsType = 'array';

            const description = paramDescMap.get(name) || `参数 ${name}`;

            params.push({
                name,
                type: tsType,
                description,
                required,
                default: defaultVal
            });
        });

        return params;
    }

    getParameters(): ToolParameter[] {
        return this._parameters;
    }

    /**
     * 执行工具方法
     *
     * @param parameters 方法参数
     * @returns 方法执行结果
     * @throws TypeValidationError 当参数类型校验失败时抛出
     */
    async run(parameters: Record<string, any>): Promise<string> {
        try {
            // 参数类型校验
            this.validateParameterTypes(parameters);
            
            // 过滤掉未提供的可选参数
            const args: any[] = [];
            this._parameters.forEach(p => {
                if (p.required || parameters[p.name] !== undefined) {
                    args.push(parameters[p.name]);
                } else if (p.default !== undefined) {
                    args.push(p.default);
                }
            });

            // 调用原方法并返回结果
            const result = this.method.apply(this.parent, args);
            return result;
        } catch (error) {
            // 提供友好的错误信息
            if (error instanceof TypeValidationError) {
                throw error;
            }
            
            // 捕获方法执行异常
            const errorMessage = error instanceof Error ? error.message : String(error);
            return `工具执行失败: ${errorMessage}`;
        }
    }

    /**
     * 验证参数类型
     *
     * @param parameters 要验证的参数对象
     * @throws TypeValidationError 当参数类型不匹配时抛出
     */
    private validateParameterTypes(parameters: Record<string, any>): void {
        for (const param of this._parameters) {
            if (parameters[param.name] !== undefined) {
                const value = parameters[param.name];
                const actualType = this.getActualType(value);
                const expectedType = param.type;
                
                if (!this.isTypeCompatible(actualType, expectedType, value)) {
                    throw new TypeValidationError(
                        `参数 "${param.name}" 类型错误: 期望 ${expectedType}, 实际得到 ${actualType}`,
                        param.name,
                        expectedType,
                        actualType,
                        value
                    );
                }
            } else if (param.required) {
                // 检查必需参数是否提供
                throw new TypeValidationError(
                    `必需参数 "${param.name}" 未提供`,
                    param.name,
                    param.type,
                    'undefined',
                    undefined
                );
            }
        }
    }

    /**
     * 获取值的实际类型
     *
     * @param value 要检查的值
     * @returns 类型字符串
     */
    private getActualType(value: any): string {
        if (value === null) return 'null';
        if (value === undefined) return 'undefined';
        if (Array.isArray(value)) return 'array';
        return typeof value;
    }

    /**
     * 检查类型是否兼容
     *
     * @param actualType 实际类型
     * @param expectedType 期望类型
     * @param value 实际值
     * @returns 是否兼容
     */
    private isTypeCompatible(actualType: string, expectedType: string, value: any): boolean {
        // 严格类型检查 - 不接受字符串形式的数字或布尔值
        return actualType === expectedType;
    }
}
